# Generated by Django 3.2 on 2022-10-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0067_auto_20221011_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget_marked_officers',
            fields=[
                ('budget_marked_officers_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_flag', models.IntegerField(max_length=7, null=True)),
                ('marked_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='budget_para',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('para_no', models.CharField(max_length=5)),
                ('financial_year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateField(null=True)),
                ('modified_on', models.DateField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('status_flag', models.IntegerField(max_length=7, null=True)),
                ('overall_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='budget_updates',
            fields=[
                ('updates_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_update_flag', models.IntegerField(max_length=3, null=True)),
                ('status_flag', models.IntegerField(max_length=7, null=True)),
                ('overall_status', models.IntegerField(max_length=7, null=True)),
                ('budget_marked_officers_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budget_marked_officers')),
            ],
        ),
        migrations.CreateModel(
            name='budget_specific_actions',
            fields=[
                ('specific_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('specific_action', models.CharField(max_length=500, null=True)),
                ('sub_specific_action', models.CharField(max_length=500, null=True)),
                ('physical_target_given', models.CharField(max_length=100, null=True)),
                ('financial_target_sanctioned', models.CharField(max_length=100, null=True)),
                ('intended_outcome', models.CharField(max_length=100, null=True)),
                ('physical_target_achieved', models.CharField(max_length=100, null=True)),
                ('financial_target_achieved', models.CharField(max_length=100, null=True)),
                ('intended_outcome_achieved', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateField(null=True)),
                ('modified_on', models.DateField(null=True)),
                ('target_date', models.DateField(max_length=8, null=True)),
                ('budget_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budget_para')),
            ],
        ),
        migrations.AddField(
            model_name='budget_marked_officers',
            name='specific_action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budget_specific_actions'),
        ),
    ]
