# Generated by Django 3.2 on 2022-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_para',
            name='action',
            field=models.CharField(default='Action Not Initiated', max_length=50),
        ),
    ]
