# Generated by Django 3.2 on 2022-11-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0069_custom_menu_icons'),
        ('budget', '0002_budget_para_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_para',
            name='compliance',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='budget_otp',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
