# Generated by Django 3.2 on 2022-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20221117_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_specific_actions',
            name='data_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='budget_specific_actions',
            name='data_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
