# Generated by Django 3.2 on 2023-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20221206_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_para',
            name='para_no',
            field=models.CharField(max_length=10),
        ),
    ]
