# Generated by Django 3.2 on 2022-09-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspects', '0088_myuser_phase_type'),
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('do_letter_no', models.CharField(max_length=200)),
                ('do_letter_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('delete_flag', models.BooleanField()),
                ('status_flag', models.PositiveSmallIntegerField()),
                ('do_path', models.FileField(upload_to='do_letter/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast')),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='do_act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('remarks', models.TextField(null=True)),
                ('reply_path', models.FileField(null=True, upload_to='do_letter/')),
                ('date_of_reply', models.DateField(auto_now_add=True, null=True)),
                ('status_flag', models.BooleanField(default=False)),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast')),
                ('id_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_letters.do_upload')),
            ],
        ),
    ]
