# Generated by Django 3.2 on 2022-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_upload',
            name='status_flag',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
