# Generated by Django 3.2 on 2022-09-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_letters', '0002_alter_do_upload_status_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='do_act',
        ),
    ]
