# Generated by Django 3.2 on 2022-09-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_letters', '0003_delete_do_act'),
    ]

    operations = [
        migrations.DeleteModel(
            name='do_upload',
        ),
    ]
