# Generated by Django 3.2 on 2022-09-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspects', '0095_auto_20220926_1921'),
        ('do_letters', '0004_delete_do_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('desig_id', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('do_letter_no', models.CharField(max_length=200)),
                ('do_letter_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('delete_flag', models.BooleanField()),
                ('status_flag', models.PositiveSmallIntegerField(default=0)),
                ('do_path', models.FileField(upload_to='do_letter/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast')),
            ],
        ),
    ]
