# Generated by Django 3.2 on 2022-09-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0095_auto_20220926_1921'),
        ('do_letters', '0005_do_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('desig_id', models.CharField(max_length=200)),
                ('remarks', models.TextField(null=True)),
                ('reply_path', models.FileField(null=True, upload_to='do_letter/')),
                ('date_of_reply', models.DateField(auto_now_add=True, null=True)),
                ('status_flag', models.BooleanField(default=False)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast')),
                ('id_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_letters.do_upload')),
            ],
        ),
    ]
