# Generated by Django 3.2 on 2022-09-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
        ('do_letters', '0006_do_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_act',
            name='desig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.AlterField(
            model_name='do_upload',
            name='desig_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
    ]
