# Generated by Django 3.2 on 2022-10-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
        ('do_letters', '0007_auto_20220929_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='do_upload',
            name='do_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='do_upload',
            name='desig_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='do_upload',
            name='do_path',
            field=models.FileField(null=True, upload_to='do_letter/'),
        ),
    ]
