# Generated by Django 3.2 on 2022-11-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20221018_1416'),
        ('do_letters', '0008_auto_20221003_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_copy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('do_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_letters.do_upload')),
            ],
        ),
    ]
