# Generated by Django 3.2 on 2022-09-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0050_inspectiontype_master_inspection_image'),
        ('einspect', '0007_einsp_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='is_scheduled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Siri_Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('empno_report', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=20)),
                ('issue_title', models.CharField(max_length=20)),
                ('issue_descp', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=10)),
                ('image_path', models.CharField(max_length=150, null=True)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('gm_flag', models.CharField(max_length=20, null=True)),
                ('drm_flag', models.CharField(max_length=20, null=True)),
                ('status_flag', models.IntegerField(default=1, null=True)),
                ('pri_index', models.IntegerField(default=0, null=True)),
                ('remark', models.CharField(default='Pending', max_length=200, null=True)),
                ('designation_code_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('rly_unit_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
