# Generated by Django 3.2 on 2022-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0008_auto_20220903_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_menu',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('m_id', models.IntegerField(null=True)),
                ('menu', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('icons', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
