# Generated by Django 3.2 on 2022-09-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0088_myuser_phase_type'),
        ('myadmin', '0050_inspectiontype_master_inspection_image'),
        ('einspect', '0009_custom_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einspection_details',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='inspection_officer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='instypeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.inspectiontype_master'),
        ),
    ]
