# Generated by Django 3.2 on 2022-09-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
        ('einspect', '0010_auto_20220905_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einspection_details',
            name='rostetrdetail_id',
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='endstn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_end', to='myadmin.station_master'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='startstn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_start', to='myadmin.station_master'),
        ),
    ]
