# Generated by Django 3.2 on 2022-09-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
        ('einspect', '0011_auto_20220907_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsp_marked',
            name='eitemid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einspection_item_detail'),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='marked_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
    ]
