# Generated by Django 3.2 on 2022-09-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
        ('einspect', '0012_auto_20220907_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_it',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rly_unit_code', models.CharField(max_length=10, null=True)),
                ('empno_report', models.CharField(max_length=20, null=True)),
                ('rlyorg', models.CharField(max_length=5, null=True)),
                ('division', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('issuetitle', models.CharField(max_length=20, null=True)),
                ('issuedescription', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('priority', models.CharField(max_length=10, null=True)),
                ('reporttime', models.DateTimeField(auto_now=True, null=True)),
                ('imagepath', models.FileField(null=True, upload_to='specification/')),
                ('remarks', models.CharField(default='Pending', max_length=100, null=True)),
                ('status_flag', models.IntegerField(default=1, null=True)),
                ('designation_code_id', models.IntegerField(null=True)),
                ('gm', models.CharField(max_length=50, null=True)),
                ('drm', models.CharField(max_length=50, null=True)),
                ('pri_index', models.IntegerField(default=0, null=True)),
                ('rly_zone', models.IntegerField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_category', models.CharField(max_length=100, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast')),
            ],
        ),
    ]
