# Generated by Django 3.2 on 2022-09-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0054_auto_20220907_1356'),
        ('einspect', '0013_issuecategory_report_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='einsp_roster',
            fields=[
                ('erosterid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fromdate', models.DateField(null=True)),
                ('todate', models.DateField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('rly_id_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='roster_detail',
            fields=[
                ('rostdetailid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('inspection_officer_id', models.CharField(max_length=30, null=True)),
                ('doi', models.DateField(null=True)),
                ('inspectionof', models.CharField(max_length=30, null=True)),
                ('section', models.CharField(max_length=30, null=True)),
                ('detail', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('inspectiontype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.inspectiontype_master')),
                ('roster_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_roster')),
            ],
        ),
    ]
