# Generated by Django 3.2 on 2022-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0014_einsp_roster_roster_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_it',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
