# Generated by Django 3.2 on 2022-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0015_alter_report_it_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_menu',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
