# Generated by Django 3.2 on 2022-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0016_custom_menu_delete_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einspection_details',
            name='inspection_note_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
