# Generated by Django 3.2 on 2022-09-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0062_loco_master'),
        ('einspect', '0017_alter_einspection_details_inspection_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways', to='myadmin.railwaylocationmaster'),
        ),
    ]
