# Generated by Django 3.2 on 2022-09-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0062_loco_master'),
        ('einspect', '0018_auto_20220923_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einsp_roster',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='einspection_details',
            name='inspection_officer_id',
        ),
        migrations.AddField(
            model_name='einsp_roster',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_einsp_roster', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.section_master'),
        ),
        migrations.AddField(
            model_name='einspection_item_detail',
            name='qncat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.inspectiontype_master'),
        ),
        migrations.AddField(
            model_name='einspection_item_detail',
            name='value_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.radio_options'),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='option1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='option2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='option3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report_it',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_report_it', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='report_it',
            name='entity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report_it',
            name='entityDetails',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report_it',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report_it',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_report_it', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='siri_report',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_Siri_Report', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='siri_report',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_Siri_Report', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='compliance_recieved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='reverted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='fromdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_einsp_roster', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='status',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_roster',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_einspection_details', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='inspected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_einspection_details', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='qtype',
            field=models.CharField(default='E-Inspection', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionare_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionare_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report_it',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report_it',
            name='reporttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roster_detail',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roster_detail',
            name='doi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roster_detail',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siri_report',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='siri_images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagepaths', models.FileField(null=True, upload_to='specification/')),
                ('report_it_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.report_it')),
            ],
        ),
    ]
