# Generated by Django 3.2 on 2022-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0019_auto_20220927_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='abnormal',
            field=models.CharField(default='No', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='ratings',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
