# Generated by Django 3.2 on 2022-10-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0066_auto_20221011_1054'),
        ('einspect', '0020_auto_20220928_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster_detail',
            name='inspection_officer_id',
        ),
        migrations.AddField(
            model_name='einsp_roster',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='report_act',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roster_detail',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.CreateModel(
            name='siri_marked',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('marked_emp_id', models.CharField(max_length=50, null=True)),
                ('compliance', models.CharField(max_length=200, null=True)),
                ('compliance_recieved_on', models.DateField(blank=True, null=True)),
                ('status_flag', models.IntegerField(max_length=1, null=True)),
                ('revert', models.CharField(max_length=50, null=True)),
                ('reverted_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_on', models.DateTimeField(blank=True, null=True)),
                ('delete_flag', models.NullBooleanField(default=False)),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('report_it_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.report_it')),
            ],
        ),
    ]
