# Generated by Django 3.2 on 2022-11-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20221018_1416'),
        ('einspect', '0021_auto_20221011_1054'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='einspection_details',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='entitydetails',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='entityid',
            field=models.CharField(max_length=50),
        ),
    ]
