# Generated by Django 3.2 on 2022-11-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0022_auto_20221114_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_master',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('lmaster', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='forward_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='parent_mark',
            field=models.IntegerField(default=-1, null=True),
        ),
        
        migrations.AddField(
            model_name='questionare_master',
            name='dependending_column',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='dependent_ques',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='depending_ques',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='revert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='remarks',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='siri_marked',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.location_master'),
        ),
    ]
