# Generated by Django 3.2 on 2022-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0023_auto_20221114_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='drm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='gm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='inspection_type',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='priority',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='einspection_item_detail',
            name='location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
