# Generated by Django 3.2 on 2022-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0024_auto_20221114_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
