# Generated by Django 3.2 on 2023-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0025_alter_einspection_item_detail_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionare_master',
            name='disable_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionare_master',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionare_master',
            name='lastmodified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
