# Generated by Django 3.2 on 2023-06-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0089_auto_20230615_1213'),
        ('einspect', '0026_auto_20230226_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown_options',
            name='column_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dropdown_options',
            name='filterName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dropdown_options',
            name='filterValue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dropdown_options',
            name='table_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast'),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='designation_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='target_date_given_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='commanDepartment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='finalizeEnd',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='einspection_details',
            name='finalizeStart',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='actionBy',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='compulsary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionare_master',
            name='question_sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.question_sub_category_master'),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='compliance',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='einsp_marked',
            name='eitemid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einspection_item_detail_fk', to='einspect.einspection_item_detail'),
        ),
        migrations.AlterField(
            model_name='einspection_details',
            name='entityid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='seperator_options',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=30, null=True)),
                ('seperator_column', models.CharField(max_length=20, null=True)),
                ('seperator', models.CharField(max_length=2, null=True)),
            ],
            options={
                'unique_together': {('table_name', 'seperator_column')},
            },
        ),
        migrations.CreateModel(
            name='einsp_forward_marked',
            fields=[
                ('forwardId', models.BigAutoField(primary_key=True, serialize=False)),
                ('designationTo', models.CharField(max_length=100, null=True)),
                ('designationBy', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('status_flag', models.IntegerField(null=True)),
                ('reply_on', models.DateField(null=True)),
                ('compliance', models.CharField(max_length=500, null=True)),
                ('forwardBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einsp_forward_marked_forwardBy', to='myadmin.level_desig')),
                ('forwardTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einsp_forward_marked_forwardTo', to='myadmin.level_desig')),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_marked')),
            ],
        ),
        migrations.CreateModel(
            name='actor_with_question',
            fields=[
                ('slno', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True, null=True)),
                ('disable_flag', models.BooleanField(default=False)),
                ('actionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.actor_details')),
                ('questionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.questionare_master')),
            ],
        ),
        migrations.CreateModel(
            name='actor_with_inspection_details',
            fields=[
                ('slno', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200, null=True)),
                ('actorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.actor_details')),
                ('einspno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einspection_details')),
            ],
        ),
    ]
