# Generated by Django 3.2 on 2023-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0027_auto_20230615_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown_options',
            name='filterValue',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
