# Generated by Django 3.2 on 2023-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0028_alter_dropdown_options_filtervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_with_inspection_details',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor_with_inspection_details',
            name='value1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='einspection_item_detail',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
