# Generated by Django 3.2 on 2023-06-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0029_auto_20230619_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor_with_inspection_details',
            name='value1',
        ),
    ]
