# Generated by Django 3.2 on 2023-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0030_remove_actor_with_inspection_details_value1'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionare_master',
            name='mixedChoices',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
