# Generated by Django 3.2 on 2023-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0031_questionare_master_mixedchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionare_master',
            name='weightage',
            field=models.IntegerField(default=1),
        ),
    ]
