# Generated by Django 3.2 on 2023-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0032_questionare_master_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionare_master',
            name='mixedChoices',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
