# Generated by Django 3.2 on 2023-06-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0092_alter_sub_category_master_sub_category'),
        ('einspect', '0033_alter_questionare_master_mixedchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsp_forward_marked',
            name='further_forward',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='einsp_forward_marked',
            name='parent_forward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_forward_marked'),
        ),
        migrations.AddField(
            model_name='einsp_forward_marked',
            name='rejected_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='einsp_marked',
            name='reject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='einsp_officers_remark',
            fields=[
                ('remark_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('reply_received', models.CharField(max_length=3000, null=True)),
                ('rejected_on', models.DateTimeField(null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('marked_desig_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_marked')),
                ('marked_no_forward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_forward_marked')),
            ],
        ),
    ]
