# Generated by Django 3.2 on 2023-09-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0101_alter_railwaylocationmaster_location_code'),
        ('einspect', '0034_auto_20230630_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_item_detail',
            name='item_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.question_sub_category_master'),
        ),
        migrations.AddField(
            model_name='einspection_item_detail',
            name='priority',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
