# Generated by Django 3.2 on 2023-09-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0035_auto_20230901_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster_detail',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='roster_detail',
            name='inspectiontype_id',
        ),
        migrations.RemoveField(
            model_name='roster_detail',
            name='roster_id',
        ),
        migrations.DeleteModel(
            name='einsp_roster',
        ),
        migrations.DeleteModel(
            name='roster_detail',
        ),
    ]
