# Generated by Django 3.2 on 2023-09-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0101_alter_railwaylocationmaster_location_code'),
        ('einspect', '0036_auto_20230904_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='einsp_roster',
            fields=[
                ('erosterid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
                ('inspection_type', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1, max_length=1, null=True)),
                ('roster_number', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastmodified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='myadmin.adminmaster')),
            ],
        ),
        migrations.CreateModel(
            name='custom_sections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='myadmin.adminmaster')),
                ('existing_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_section', to='myadmin.section_master')),
                ('from_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='myadmin.station_master')),
                ('to_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='myadmin.station_master')),
            ],
        ),
        migrations.CreateModel(
            name='custom_inspection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_name', models.CharField(max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('disable_flag', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_insp', to='myadmin.adminmaster')),
            ],
        ),
        migrations.CreateModel(
            name='custom_desig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(default=False)),
                ('disable_flag', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_desig', to='myadmin.adminmaster')),
                ('desig_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
