# Generated by Django 3.2 on 2023-09-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0037_custom_desig_custom_inspection_custom_sections_einsp_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='roster_detail',
            fields=[
                ('rostdetailid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('doi', models.DateField(blank=True, null=True)),
                ('add_data_insp', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('custom_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.custom_desig')),
                ('custom_inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.custom_inspection')),
                ('custom_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.custom_sections')),
                ('roster_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_roster')),
            ],
        ),
    ]
