# Generated by Django 3.2 on 2023-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0038_roster_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='masterTableFlag',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
