# Generated by Django 3.2 on 2023-09-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0039_einspection_details_mastertableflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionare_master',
            name='activity',
            field=models.CharField(max_length=1000),
        ),
    ]
