# Generated by Django 3.2 on 2023-11-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0103_auto_20230925_1408'),
        ('einspect', '0040_alter_questionare_master_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='einspection_department_display',
            fields=[
                ('disp_no', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('lastmodified_on', models.DateField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast')),
                ('instypeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.inspectiontype_master')),
            ],
        ),
    ]
