# Generated by Django 3.2 on 2023-11-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0041_einspection_department_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='einsp_multi_location',
            fields=[
                ('location_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=5, null=True)),
                ('einspno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einspection_details')),
            ],
        ),
    ]
