# Generated by Django 3.2 on 2023-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0042_einsp_multi_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_desig',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_inspection',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_sections',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roster_detail',
            name='close_Remark',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='roster_detail',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
