# Generated by Django 3.2 on 2024-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0043_auto_20231130_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einspection_details',
            name='abnormal',
            field=models.CharField(default='No', max_length=100, null=True),
        ),
    ]
