# Generated by Django 3.2 on 2025-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0044_alter_einspection_details_abnormal'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_details',
            name='commanDesignation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='einspection_coach_details',
            fields=[
                ('location_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10, null=True)),
                ('einspno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einspection_details')),
            ],
        ),
    ]
