# Generated by Django 3.2 on 2025-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0045_auto_20250508_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='einspection_coach_details',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
