# Generated by Django 3.2 on 2022-09-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insp_details',
            fields=[
                ('insp_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('mom_note_no', models.CharField(blank=True, max_length=40, null=True)),
                ('note_last', models.IntegerField(default=0, null=True)),
                ('mom_date', models.DateField(null=True)),
                ('mom_title', models.CharField(max_length=200, null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('mom_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('item_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('item_heading', models.CharField(max_length=100, null=True)),
                ('item_subheading', models.CharField(max_length=100, null=True)),
                ('item_description', models.CharField(max_length=500, null=True)),
                ('item_decision', models.CharField(max_length=500, null=True)),
                ('target_date', models.DateField(null=True)),
                ('type', models.CharField(max_length=5, null=True)),
                ('des_id', models.CharField(max_length=10, null=True)),
                ('item_priority', models.CharField(max_length=1, null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('insp_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom.insp_details')),
            ],
        ),
        migrations.CreateModel(
            name='Marked_Members',
            fields=[
                ('marked_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('reply_text', models.CharField(max_length=500, null=True)),
                ('reply_file', models.FileField(upload_to='documents/')),
                ('reply_on', models.DateField(null=True)),
                ('status_flag', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('item_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom.item_details')),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='Reject_remark',
            fields=[
                ('remark_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('reply_received', models.CharField(max_length=50, null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('reject_on', models.DateTimeField(null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('marked_desig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom.marked_members')),
            ],
        ),
        migrations.CreateModel(
            name='Insp_members',
            fields=[
                ('member_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_flag', models.IntegerField(default=0)),
                ('insp_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom.insp_details')),
                ('member_desig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='copydealt_mail',
            fields=[
                ('mail_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('send_to', models.CharField(max_length=2000, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('area', models.CharField(max_length=10, null=True)),
                ('insp_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom.insp_details')),
            ],
        ),
    ]
