# Generated by Django 3.2 on 2022-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_details',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
