# Generated by Django 3.2 on 2022-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0002_insp_details_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_subheading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
