# Generated by Django 3.2 on 2022-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0003_auto_20221003_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_subheading',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
