# Generated by Django 3.2 on 2022-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0004_alter_item_details_item_subheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting_typelist',
            fields=[
                ('type_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='insp_details',
            name='meeting_type',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
