# Generated by Django 3.2 on 2022-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0005_auto_20221114_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='reject_remark',
            name='file_received',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_decision',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_heading',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_subheading',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
