# Generated by Django 3.2 on 2022-12-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0006_auto_20221206_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_decision',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_heading',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_subheading',
            field=models.TextField(null=True),
        ),
    ]
