# Generated by Django 3.2 on 2023-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0007_auto_20221219_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_members',
            name='other_members',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
