# Generated by Django 3.2 on 2023-03-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0073_auto_20230226_0910'),
        ('mom', '0008_insp_members_other_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_typelist',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='meeting_typelist',
            name='default_flag',
            field=models.IntegerField(default=1),
        ),
    ]
