# Generated by Django 3.2 on 2023-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0009_auto_20230310_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insp_details',
            name='mom_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
