# Generated by Django 3.2 on 2023-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0010_auto_20230320_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insp_details',
            name='meeting_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='insp_details',
            name='mom_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
