# Generated by Django 3.2 on 2024-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0011_auto_20230605_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_details',
            name='officer_desig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insp_details',
            name='officer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insp_details',
            name='station_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insp_details',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
