# Generated by Django 3.2 on 2024-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0012_auto_20240529_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_details',
            name='link_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='slno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item_details',
            name='table_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='item_details',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='marked_members',
            name='action_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marked_members',
            name='priority',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='marked_members',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='marked_members',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='copydealt_mail',
            name='send_to',
            field=models.TextField(null=True),
        ),
    ]
