# Generated by Django 3.2 on 2024-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0013_auto_20240531_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_members',
            name='reply_text',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
