"""
Django settings for Admin_inspection project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(n1t1-bcy6*u0+liw&3_2d6$$$6zfksr0fb4hau0xdivfeuvz0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# X_FRAME_OPTIONS = 'ALLOW-FROM https://deveins.indianrailways.gov.in'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myadmin',
    'inspects',
    'einspect',
    'mom',
    'do_letters',
    'budget',
    'mails',
    'home_page',
    'api',
     'corsheaders',
     'rest_framework',
    'rest_framework_simplejwt' 
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
    
    # 'csp.middleware.CSPMiddleware',
]
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS ='SAMEORIGIN'
ROOT_URLCONF = 'misiProject.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

# WSGI_APPLICATION = 'Admin_inspection.wsgi.application'
WSGI_APPLICATION = 'misiProject.wsgi.application'
AUTH_USER_MODEL = "inspects.MyUser"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'misiprod_070824v1139',
        'USER': 'postgres',
        'PASSWORD': 'Post@1234',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'users': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cris-cr',
        'USER': 'criscr456',
        'PASSWORD': 'cV752O8404',
        'HOST': '10.64.24.63',
        'PORT': '3306',        
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# STATIC_URL = '/static/'
MEDIA_URL = 'media/'
STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'inspects/static'),
    # os.path.join(BASE_DIR, 'einspect/static'),
    # os.path.join(BASE_DIR, 'do_letters/static'),
    # os.path.join(BASE_DIR, 'mom/static')

   
]
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"),]

# Email configuration
EMAIL_HOST = '10.77.32.47'
EMAIL_PORT = 25
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'mfgcris@cris.org.in'
EMAIL_HOST_PASSWORD = 'cris@2022##'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
LOGIN_URL = '/login'
# # Email configuration
# EMAIL_HOST = 'pcpctrlaymailsrvr.cloud.cris.in'
# # '10.77.32.48'
# EMAIL_PORT = 25
# # EMAIL_USE_TLS = False
# # EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'mfgcris@cris.org.in'
# EMAIL_HOST_PASSWORD = 'cris@2022'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = 'smtp.zoho.in'
# # EMAIL_HOST_USER = 'rishabh.singh_1@zohomail.in'
# # EMAIL_HOST_PASSWORD = '5RMqdHiFGYFk'
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True

# SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True



# SERVER_EMAIL='root@localhost'
# SESSION_COOKIE_SECURE = True

# Content-Security-Policy: frame-ancestors 'self'

# CSP_DEFAULT_SRC = ("'none'",)
# CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com')
# CSP_SCRIPT_SRC = ("'self'",)
# CSP_FONT_SRC = ("'self'", 'fonts.gstatic.com')
# CSP_IMG_SRC = ("'self'",)

# CSP_REPORT_URI = '<add your reporting uri>'
  
# # default source as self
# CSP_DEFAULT_SRC = ("'self'", )
  
# # style from our domain and bootstrapcdn
# CSP_STYLE_SRC = ("'self'", 
#     "stackpath.bootstrapcdn.com")
  
# # scripts from our domain and other domains
# CSP_SCRIPT_SRC = ("'self'",
#     "ajax.cloudflare.com",
#     "static.cloudflareinsights.com",
#     "www.google-analytics.com",
#     "ssl.google-analytics.com",
#     "cdn.ampproject.org",
#     "www.googletagservices.com",
#     "pagead2.googlesyndication.com")
  
# # images from our domain and other domains
# CSP_IMG_SRC = ("'self'",
#     "www.google-analytics.com",
#     "raw.githubusercontent.com",
#     "googleads.g.doubleclick.net")
  
# # loading manifest, workers, frames, etc
# CSP_FONT_SRC = ("'self'", )
# CSP_CONNECT_SRC = ("'self'", 
#     "www.google-analytics.com" )
# CSP_OBJECT_SRC = ("'self'", )
# CSP_BASE_URI = ("'self'", )
# CSP_FRAME_ANCESTORS = ("'self'", )
# CSP_FORM_ACTION = ("'self'", )
# CSP_INCLUDE_NONCE_IN = ('script-src', )
# CSP_MANIFEST_SRC = ("'self'", )
# CSP_WORKER_SRC = ("'self'", )
# CSP_MEDIA_SRC = ("'self'", )



CORS_ORIGIN_ALLOW_ALL =  True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


############  logging 


import logging
# USE_X_FORWARDED_FOR = True
from inspects.logging_middleware import CustomFormatter
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'custom',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'debug.log',
            'maxBytes': 100 * 1024 * 1024, 
            'formatter': 'custom',
        },
    },
    'formatters': {
        'custom': {
            '()': CustomFormatter,
        },
    },
    # 'loggers': {
    #     'django': {
    #         'handlers': ['console', 'file'],
    #         'level': 'INFO',
    #         'propagate': True,
    #     },
    # },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',  # Change to 'WARNING' or higher
            'propagate': True,
        },
    }
}

'inspects.custom_middleware.SessionMiddleware',
'inspects.logging_middleware.RequestLoggingMiddleware',



