# Generated by Django 3.2 on 2023-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railmadad_cause_graph',
            name='name111',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
