# Generated by Django 3.2 on 2023-02-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_railmadad_cause_graph_name111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railmadad_cause_graph',
            name='name111',
        ),
    ]
