# Generated by Django 3.2 on 2023-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_railmadad_cause_graph_name111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_reliability',
            name='AF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability',
            name='TD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability',
            name='average_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability_month',
            name='AF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability_month',
            name='TD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability_month',
            name='average_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset_reliability_month',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capex',
            name='serial_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cause_service_output',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='S_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='punctuality_service_output',
            name='nlt_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='punctuality_service_output',
            name='train_count',
            field=models.IntegerField(),
        ),
    ]
