# Generated by Django 3.2 on 2023-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230313_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='wagon_breakup',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cum_prev', models.IntegerField(default=0, null=True)),
                ('target', models.CharField(default='NA', max_length=10, null=True)),
                ('monthly_achvd', models.IntegerField(default=0, null=True)),
                ('cum_achvd', models.IntegerField(default=0, null=True)),
                ('same_month_of_previous_year', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
