# Generated by Django 3.2 on 2023-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wagon_breakup'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_reliability',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset_reliability_month',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capex',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cause_service_output',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='earnings',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loading_commodity',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loading_overall',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loading_zonal',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punctuality_service_output',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='safety',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wagon',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
    ]
