# Generated by Django 3.2 on 2022-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0068_auto_20221018_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='copyto_mails',
            fields=[
                ('mail_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender_desig', models.CharField(max_length=15, null=True)),
                ('doc_id', models.BigIntegerField(null=True)),
                ('doc_table', models.CharField(max_length=10)),
                ('receiver_id', models.CharField(max_length=2000, null=True)),
                ('receiver_desig', models.CharField(max_length=2000, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('area_flag', models.IntegerField(default=0)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
