# Generated by Django 3.2 on 2022-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyto_mails',
            name='sender_desig',
        ),

    ]
