# Generated by Django 3.2 on 2022-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20221114_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyto_mails',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
