# Generated by Django 3.2 on 2022-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_copyto_mails_reminder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyto_mails',
            name='receiver_desig',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='copyto_mails',
            name='receiver_id',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
