# Generated by Django 3.2 on 2023-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20221114_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyto_mails',
            name='receiver_desig',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='copyto_mails',
            name='receiver_id',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
