# Generated by Django 3.2 on 2023-03-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_auto_20230307_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyto_mails',
            name='noted_by',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='copyto_mails',
            name='noted_flag',
            field=models.IntegerField(default=0),
        ),
    ]
