# Generated by Django 3.2 on 2025-06-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0118_feedback_data'),
        ('mails', '0006_auto_20230329_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_data_copyto_mails',
            fields=[
                ('mail_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('doc_id', models.BigIntegerField(null=True)),
                ('doc_table', models.CharField(max_length=10)),
                ('receiver_id', models.CharField(max_length=6000, null=True)),
                ('receiver_desig', models.CharField(max_length=6000, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('area_flag', models.IntegerField(default=0)),
                ('reminder_count', models.IntegerField(default=0)),
                ('noted_flag', models.IntegerField(default=0)),
                ('noted_by', models.CharField(max_length=6000, null=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
