# Generated by Django 3.2 on 2025-06-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_deleted_data_copyto_mails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deleted_data_copyto_mails',
        ),
    ]
