# Generated by Django 3.2 on 2022-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0086_item_details_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='empno',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
