# Generated by Django 3.2 on 2022-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0087_alter_user_request_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phase_type',
            field=models.CharField(default='1', max_length=1, null=True),
        ),
    ]
