# Generated by Django 3.2 on 2022-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0088_myuser_phase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_officers',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
