# Generated by Django 3.2 on 2022-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0089_alter_marked_officers_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insp_mail_details',
            name='send_desig',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
