# Generated by Django 3.2 on 2022-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0090_alter_insp_mail_details_send_desig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrigendum_report',
            old_name='status',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='corrigendum_report',
            name='new_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrigendum_report',
            name='old_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrigendum_report',
            name='status_flag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
