# Generated by Django 3.2 on 2022-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0091_auto_20220912_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='designation_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='empnumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='old_value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
