# Generated by Django 3.2 on 2022-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0092_auto_20220916_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='document/')),
                ('requestDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
