# Generated by Django 3.2 on 2022-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0093_email_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_multi_location',
            name='table_from',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
