# Generated by Django 3.2 on 2022-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0094_insp_multi_location_table_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
