# Generated by Django 3.2 on 2022-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0095_auto_20220926_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_request',
            name='rly_id',
            field=models.IntegerField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='email_request',
            name='file',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
