# Generated by Django 3.2 on 2022-10-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
        ('inspects', '0096_auto_20221004_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_request',
            name='rly_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailrequestrailid', to='myadmin.railwaylocationmaster'),
        ),
    ]
