# Generated by Django 3.2 on 2022-10-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
        ('inspects', '0097_alter_email_request_rly_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_activty',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='inspection_note_no',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='inspection_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='schedule_marked1',
            fields=[
                ('marked_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('marked_emp', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('act_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.event_activty')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.events')),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
