# Generated by Django 3.2 on 2022-10-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0098_auto_20221011_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insp_Accompany',
            fields=[
                ('accompany_no', models.AutoField(primary_key=True, serialize=False)),
                ('accompany', models.CharField(max_length=40, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('inspection_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.inspection_details')),
            ],
        ),
    ]
