# Generated by Django 3.2 on 2022-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0099_insp_accompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_checklist',
            name='version',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
