# Generated by Django 3.2 on 2022-11-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20221018_1416'),
        ('inspects', '0100_inspection_checklist_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='commanlogin',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50, null=True)),
                ('sites', models.CharField(max_length=20, null=True)),
                ('auth', models.CharField(max_length=50, null=True)),
                ('pwd', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspection_checklist',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast'),
        ),
    ]
