# Generated by Django 3.2 on 2022-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0101_auto_20221114_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_multi_location',
            name='item_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
