# Generated by Django 3.2 on 2022-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0102_insp_multi_location_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sso_Session_Key',
            fields=[
                ('s_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('pub_key', models.CharField(max_length=10, null=True)),
                ('pri_key', models.CharField(max_length=10, null=True)),
                ('application', models.CharField(max_length=5, null=True)),
                ('value', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sso_User_Details',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sso_user', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=5, null=True)),
                ('app_user', models.CharField(max_length=40)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
