# Generated by Django 3.2 on 2022-12-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0070_auto_20221206_1154'),
        ('inspects', '0103_sso_session_key_sso_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_checklist',
            name='version',
            field=models.IntegerField(default='1', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='category_add',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=15, null=True)),
                ('created_by', models.CharField(max_length=15, null=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast')),
            ],
        ),
    ]
