# Generated by Django 3.2 on 2022-12-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0070_auto_20221206_1154'),
        ('inspects', '0104_auto_20221207_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='irpsm_workplan_mstr',
            fields=[
                ('uwid', models.IntegerField(primary_key=True, serialize=False)),
                ('curr_cost', models.FloatField(null=True)),
                ('expenditure_curr_finyear', models.FloatField(null=True)),
                ('fin_progress', models.FloatField(null=True)),
                ('phy_progress', models.FloatField(null=True)),
                ('plan_head', models.CharField(max_length=50, null=True)),
                ('work_category', models.CharField(max_length=50, null=True)),
                ('yearmonth', models.IntegerField()),
                ('updatedate', models.DateTimeField(null=True)),
                ('receiving_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=12, null=True)),
                ('Assigned_on', models.DateTimeField(auto_now=True, null=True)),
                ('Relieved_on', models.DateTimeField(auto_now=True, null=True)),
                ('Relieved_by', models.CharField(max_length=50, null=True)),
                ('Assigned_by', models.CharField(max_length=50, null=True)),
                ('desig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='succdesig_id', to='myadmin.level_desig')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predparent_id', to='myadmin.level_desig')),
            ],
        ),
    ]
