# Generated by Django 3.2 on 2022-12-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0105_history_table_irpsm_workplan_mstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='curr_cost',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='expenditure_curr_finyear',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='fin_progress',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='phy_progress',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='plan_head',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='receiving_time',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='updatedate',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='work_category',
        ),
        migrations.RemoveField(
            model_name='irpsm_workplan_mstr',
            name='yearmonth',
        ),
    ]
