# Generated by Django 3.2 on 2022-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0106_auto_20221215_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='curr_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='expenditure_curr_finyear',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='fin_progress',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='phy_progress',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='plan_head',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='receiving_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='updatedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='work_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='irpsm_workplan_mstr',
            name='yearmonth',
            field=models.IntegerField(default=202210),
            preserve_default=False,
        ),
    ]
