# Generated by Django 3.2 on 2022-12-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0109_irpsm_workplan_mstr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='irpsm_workplan_mstr',
        ),
    ]
