# Generated by Django 3.2 on 2022-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0110_delete_irpsm_workplan_mstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='irpsm_workplan_mstr',
            fields=[
                ('uwid', models.IntegerField(primary_key=True, serialize=False)),
                ('curr_cost', models.FloatField(null=True)),
                ('expenditure_curr_finyear', models.FloatField(null=True)),
                ('fin_progress', models.FloatField(null=True)),
                ('phy_progress', models.FloatField(null=True)),
                ('plan_head', models.CharField(max_length=50, null=True)),
                ('work_category', models.CharField(max_length=50, null=True)),
                ('yearmonth', models.IntegerField()),
                ('updatedate', models.DateTimeField(null=True)),
                ('receiving_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
