# Generated by Django 3.2 on 2022-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0114_alter_marked_officers_compliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_officers_forward',
            name='compliance_forward',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
