# Generated by Django 3.2 on 2022-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0115_alter_marked_officers_forward_compliance_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_officers',
            name='revert',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
