# Generated by Django 3.2 on 2023-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0116_alter_marked_officers_revert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='desig_longdesc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
