# Generated by Django 3.2 on 2023-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0118_alter_empmast_desig_longdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='desig_longdesc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
