# Generated by Django 3.2 on 2023-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0119_alter_empmast_desig_longdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_subtitle',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='item_title',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='observation',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
