# Generated by Django 3.2 on 2023-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0120_auto_20230203_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='myuser_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
