# Generated by Django 3.2 on 2023-02-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0121_alter_empmast_myuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmast',
            name='desig_id',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='myuser_id',
        ),
    ]
