# Generated by Django 3.2 on 2023-02-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0122_auto_20230216_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
