# Generated by Django 3.2 on 2023-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0123_auto_20230226_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_details',
            name='tbl_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='inspection_title',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
