# Generated by Django 3.2 on 2023-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0124_auto_20230307_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='link_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
