# Generated by Django 3.2 on 2023-04-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0125_item_details_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_officers',
            name='compliance',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='marked_officers_forward',
            name='compliance_forward',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='officers_remark',
            name='reply_received',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
