# Generated by Django 3.2 on 2023-04-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0126_auto_20230410_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='final_submit_on',
            field=models.DateField(null=True),
        ),
    ]
