# Generated by Django 3.2 on 2023-04-17 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0127_inspection_details_final_submit_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='guest_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
