# Generated by Django 3.2 on 2023-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0128_myuser_guest_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='officer_desig',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='officer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='station_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
