# Generated by Django 3.2 on 2023-05-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0129_auto_20230503_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='action_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='target_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='guest_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='target_compliance',
            fields=[
                ('target_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_date', models.DateField(null=True)),
                ('status_flag', models.IntegerField(null=True)),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers')),
            ],
        ),
    ]
