# Generated by Django 3.2 on 2023-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0130_auto_20230508_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_compliance',
            name='rejected_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='reply_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='reply_sent',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
