# Generated by Django 3.2 on 2023-05-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0131_auto_20230511_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='target_status',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_flag', models.IntegerField(null=True)),
                ('reply_sent', models.CharField(max_length=3000, null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('rejected_on', models.DateTimeField(null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('target_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.target_compliance')),
            ],
        ),
    ]
