# Generated by Django 3.2 on 2023-05-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0081_auto_20230519_1016'),
        ('inspects', '0132_target_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_compliance',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='pending_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='task_descp',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='task_flag',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='task_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
