# Generated by Django 3.2 on 2023-06-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0133_auto_20230523_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='marked_officers_forward',
            name='further_forward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers_forward'),
        ),
        migrations.AddField(
            model_name='marked_officers_forward',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
