# Generated by Django 3.2 on 2023-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0134_auto_20230605_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='insp_accompany',
            name='update_status',
            field=models.CharField(default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='insp_multi_location',
            name='update_status',
            field=models.CharField(default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='item_details',
            name='update_status',
            field=models.CharField(default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='update_status',
            field=models.CharField(default='T', max_length=1),
        ),
    ]
