# Generated by Django 3.2 on 2023-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0135_auto_20230607_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_details',
            name='inspection_note_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='officer_desig',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
