# Generated by Django 3.2 on 2023-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0136_auto_20230607_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmast',
            name='SSOUid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='SessionId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
