# Generated by Django 3.2 on 2023-06-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0091_auto_20230626_1922'),
        ('inspects', '0137_auto_20230621_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tour_description', models.CharField(max_length=1000, null=True)),
                ('accompanied_by', models.CharField(max_length=1000, null=True)),
                ('document', models.FileField(max_length=1000, null=True, upload_to='static/document_upload/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('letter_no', models.CharField(max_length=1000, null=True)),
                ('status_flag', models.IntegerField(default=0, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('approving_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_officer', to='myadmin.level_desig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='inspects.empmast')),
                ('inspecting_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspecting_officer', to='myadmin.level_desig')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_by', to='inspects.empmast')),
                ('looking_after_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looking_after_officer', to='myadmin.level_desig')),
                ('modified_new_schedule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.schedule_detail')),
                ('recommending_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommending_officer', to='myadmin.level_desig')),
            ],
        ),
        migrations.CreateModel(
            name='tour_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('mode', models.CharField(max_length=100, null=True)),
                ('trans_detail', models.CharField(max_length=100, null=True)),
                ('arr_time', models.TimeField(null=True)),
                ('dep_time', models.TimeField(null=True)),
                ('from_location', models.CharField(max_length=100, null=True)),
                ('to', models.CharField(max_length=100, null=True)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('schedule_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.schedule_detail')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_remarks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_taken', models.IntegerField(default=0)),
                ('rem_date', models.DateField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('letter_no', models.CharField(max_length=1000, null=True)),
                ('remarks_by_officer', models.CharField(max_length=1000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_remarks', to='inspects.empmast')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='myadmin.level_desig')),
                ('schedule_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.schedule_detail')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_marked',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('view_flag', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_marked', to='inspects.empmast')),
                ('marked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
                ('schedule_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.schedule_detail')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, null=True)),
                ('value', models.CharField(max_length=1000, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('last_mod_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_location', to='inspects.empmast')),
                ('last_mod_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_mod_by_location', to='inspects.empmast')),
                ('schedule_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.schedule_detail')),
            ],
        ),
    ]
