# Generated by Django 3.2 on 2023-07-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0093_actor_details_viewactorname'),
        ('inspects', '0138_schedule_detail_schedule_location_schedule_marked_schedule_remarks_tour_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_detail',
            name='forwarded_to_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_to_officer', to='myadmin.level_desig'),
        ),
    ]
