# Generated by Django 3.2 on 2023-07-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0034_auto_20230630_1521'),
        ('inspects', '0139_schedule_detail_forwarded_to_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='markofcRemarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='sl_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target_compliance',
            name='marked_einsp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einsp_marked'),
        ),
    ]
