# Generated by Django 3.2 on 2023-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0140_auto_20230712_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='insp_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='item_sections',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_details',
            name='location_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='location_table',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='action_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='officer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
