# Generated by Django 3.2 on 2023-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0141_auto_20230720_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='hrms_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=20, null=True)),
                ('hrmsid', models.CharField(max_length=20, null=True)),
                ('token', models.CharField(max_length=500, null=True)),
                ('SessionId', models.CharField(blank=True, max_length=500, null=True)),
                ('SSOUid', models.CharField(blank=True, max_length=500, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
