# Generated by Django 3.2 on 2023-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0142_hrms_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='location_val',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
