# Generated by Django 3.2 on 2023-08-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0098_level_desig_hierarchy_level'),
        ('inspects', '0143_item_details_location_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='divid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_div_id', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='item_details',
            name='hqid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_rly_id', to='myadmin.railwaylocationmaster'),
        ),
    ]
