# Generated by Django 3.2 on 2023-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0144_auto_20230811_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='marked_officers',
            name='marked_on',
            field=models.DateTimeField(null=True),
        ),
    ]
