# Generated by Django 3.2 on 2023-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0145_marked_officers_marked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrms_logs',
            name='empno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
