# Generated by Django 3.2 on 2023-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0146_alter_hrms_logs_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insp_accompany',
            name='accompany',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
