# Generated by Django 3.2 on 2023-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0147_alter_insp_accompany_accompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_details',
            name='station_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
