# Generated by Django 3.2 on 2023-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0148_alter_inspection_details_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marked_officers',
            name='add_status',
            field=models.IntegerField(default=0),
        ),
    ]
