# Generated by Django 3.2 on 2023-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0149_marked_officers_add_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='good_work',
            field=models.BooleanField(default=False),
        ),
    ]
