# Generated by Django 3.2 on 2024-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0150_inspection_details_good_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_history',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('browser_type', models.CharField(max_length=100, null=True)),
                ('os_type', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=20, null=True)),
                ('login_date_time', models.DateTimeField(auto_now=True)),
                ('logout_date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_mgmt',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
