# Generated by Django 3.2 on 2024-08-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0151_login_history_session_mgmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='addendum',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compliance', models.CharField(max_length=3000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('item_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.item_details')),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers')),
            ],
        ),
    ]
