# Generated by Django 3.2 on 2024-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0152_addendum'),
    ]

    operations = [
        migrations.CreateModel(
            name='August_safety_drive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_id', models.CharField(max_length=50, null=True)),
                ('inspection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('officer_desig', models.CharField(blank=True, max_length=1000, null=True)),
                ('officer_post_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_grade_code', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_posted_in', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('officer_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('insp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('insp_date_field', models.DateTimeField(blank=True, null=True)),
                ('place_of_insp', models.CharField(blank=True, max_length=500, null=True)),
                ('zone_of_insp', models.CharField(blank=True, max_length=50, null=True)),
                ('div_of_insp', models.CharField(blank=True, max_length=200, null=True)),
                ('type_of_insp', models.CharField(blank=True, max_length=200, null=True)),
                ('shortcomings', models.CharField(blank=True, max_length=5000, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=2000, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
