# Generated by Django 3.2 on 2024-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0153_august_safety_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='august_safety_drive',
            name='divcode_of_insp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
