# Generated by Django 3.2 on 2024-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0154_august_safety_drive_divcode_of_insp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='august_safety_drive',
            name='place_of_insp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
