# Generated by Django 3.2 on 2024-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0155_alter_august_safety_drive_place_of_insp'),
    ]

    operations = [
        migrations.AddField(
            model_name='august_safety_drive',
            name='trx_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
