# Generated by Django 3.2 on 2024-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0156_august_safety_drive_trx_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='august_safety_drive',
            name='system_division_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='august_safety_drive',
            name='system_division_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
