# Generated by Django 3.2 on 2024-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0157_auto_20240830_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='august_safety_drive',
            name='insp_date_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
