# Generated by Django 3.2 on 2024-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0159_sept_safety_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sept_safety_drive',
            name='trx_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
