# Generated by Django 3.2 on 2024-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0160_alter_sept_safety_drive_trx_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sept_safety_drive',
            name='shortcomings',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
