# Generated by Django 3.2 on 2025-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0161_alter_sept_safety_drive_shortcomings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety_drive',
            fields=[
                ('drive_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('mobile', models.CharField(max_length=15)),
                ('officer_name', models.CharField(max_length=50)),
                ('officer_desig', models.CharField(max_length=50)),
                ('officer_post_grade', models.CharField(max_length=50)),
                ('officer_posted_in', models.CharField(max_length=50)),
                ('insp_date', models.DateTimeField()),
                ('place_of_insp', models.CharField(max_length=200)),
                ('hqid', models.CharField(max_length=10, null=True)),
                ('divid', models.CharField(max_length=10, null=True)),
                ('type_of_insp', models.CharField(max_length=500)),
                ('shortcomings', models.CharField(max_length=5000)),
                ('action_taken', models.CharField(max_length=2000)),
                ('comments', models.CharField(max_length=2000)),
                ('status_flag', models.CharField(blank=True, default=1, max_length=1)),
                ('delete_flag', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
