# Generated by Django 3.2 on 2025-06-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0165_deleted_data_insp_accompany_deleted_data_insp_multi_location_deleted_data_inspection_details_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleted_data_insp_multi_location',
            name='inspection_no',
        ),
        migrations.RemoveField(
            model_name='deleted_data_inspection_details',
            name='inspection_officer',
        ),
        migrations.RemoveField(
            model_name='deleted_data_item_details',
            name='inspection_no',
        ),
        migrations.RemoveField(
            model_name='deleted_data_marked_officers_forward',
            name='further_forward',
        ),
        migrations.RemoveField(
            model_name='deleted_data_marked_officers_forward',
            name='marked_no',
        ),
        migrations.RemoveField(
            model_name='deleted_data_marked_officers_forward',
            name='marked_to_forward',
        ),
        migrations.RemoveField(
            model_name='deleted_data_marked_officers_forward',
            name='myuser_id',
        ),
        migrations.RemoveField(
            model_name='deleted_data_mrked_officers',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='deleted_data_mrked_officers',
            name='marked_to',
        ),
        migrations.RemoveField(
            model_name='deleted_data_mrked_officers',
            name='myuser_id',
        ),
        migrations.RemoveField(
            model_name='deleted_data_target_compliance',
            name='marked_einsp',
        ),
        migrations.RemoveField(
            model_name='deleted_data_target_compliance',
            name='marked_no',
        ),
        migrations.RemoveField(
            model_name='deleted_data_target_status',
            name='target_no',
        ),
        migrations.DeleteModel(
            name='deleted_data_Insp_Accompany',
        ),
        migrations.DeleteModel(
            name='deleted_data_Insp_multi_location',
        ),
        migrations.DeleteModel(
            name='deleted_data_inspection_details',
        ),
        migrations.DeleteModel(
            name='deleted_data_Item_details',
        ),
        migrations.DeleteModel(
            name='deleted_data_Marked_Officers_forward',
        ),
        migrations.DeleteModel(
            name='deleted_data_Mrked_Officers',
        ),
        migrations.DeleteModel(
            name='deleted_data_target_compliance',
        ),
        migrations.DeleteModel(
            name='deleted_data_target_status',
        ),
    ]
