# Generated by Django 3.2 on 2025-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0167_deleted_data_insp_accompany_deleted_data_insp_multi_location_deleted_data_inspection_details_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='approval_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
