# Generated by Django 3.2 on 2022-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0049_auto_20220901_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype_master',
            name='inspection_image',
            field=models.ImageField(blank=True, null=True, upload_to='images11/'),
        ),
    ]
