# Generated by Django 3.2 on 2022-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0051_alter_inspectiontype_master_statuschecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='parent_id',
            field=models.CharField(max_length=10),
        ),
    ]
