# Generated by Django 3.2 on 2022-09-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0052_alter_inspectiontype_master_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningroom_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='train_master',
            name='trainowngrly2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_trainowngrly2', to='myadmin.station_master'),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='stndest_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_stndest_code', to='myadmin.station_master'),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='stnsource_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_stnsource_code', to='myadmin.station_master'),
        ),
    ]
