# Generated by Django 3.2 on 2022-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0055_remove_section_master_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='shortcode',
            field=models.CharField(max_length=10),
        ),
    ]
