# Generated by Django 3.2 on 2022-09-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0056_alter_inspectiontype_master_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='head_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
