# Generated by Django 3.2 on 2022-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0057_level_desig_head_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='parent_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
