# Generated by Django 3.2 on 2022-09-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0058_railwaylocationmaster_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningroom_master',
            name='division_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='runningroom_master',
            name='railway_code',
            field=models.CharField(max_length=10, null=True),
        ),
     
      
        migrations.AddField(
            model_name='section_master',
            name='via',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station_master',
            name='division_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='station_master',
            name='railway_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='station_master',
            name='station_cat',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='station_master',
            name='station_cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.stationcat_master'),
        ),
        migrations.AddField(
            model_name='train_master',
            name='division_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='train_master',
            name='railway_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
