# Generated by Django 3.2 on 2022-10-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_master',
            name='endkm',
        ),
        migrations.RemoveField(
            model_name='section_master',
            name='startkm',
        ),
    ]
