# Generated by Django 3.2 on 2022-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0066_auto_20221004_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmast',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
