# Generated by Django 3.2 on 2022-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0067_departmast_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='level_desig',
            name='user_role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
