# Generated by Django 3.2 on 2022-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20221010_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_master',
            name='passing_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='train_master',
            name='passing_rly',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
