# Generated by Django 3.2 on 2022-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0069_auto_20221018_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_menu',
            name='icons',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
