# Generated by Django 3.2 on 2022-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0070_custom_menu_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_master',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post_master',
            name='pc7_levelmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_master',
            name='pc7_levelmin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
