# Generated by Django 3.2 on 2022-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0071_auto_20221122_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
    ]
