# Generated by Django 3.2 on 2022-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0072_auto_20221122_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Railwayunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_description', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Unit_shortcode', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
