# Generated by Django 3.2 on 2022-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0047_level_desig_temp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmaster',
            name='designation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='adminmaster',
            name='emp_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adminmaster',
            name='user_id',
            field=models.ImageField(max_length=10, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='level_desig',
            name='d_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
