# Generated by Django 3.2 on 2022-09-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0048_auto_20220901_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmaster',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.locationmaster'),
        ),
    ]
