# Generated by Django 3.2 on 2022-09-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0050_inspectiontype_master_inspection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='statuschecklist',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
