# Generated by Django 3.2 on 2022-09-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0053_auto_20220907_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='entity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section_master',
            name='secend_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_secend_code', to='myadmin.station_master'),
        ),
        migrations.AlterField(
            model_name='section_master',
            name='secstart_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_master_secstart_code', to='myadmin.station_master'),
        ),

    ]
