# Generated by Django 3.2 on 2022-09-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0054_auto_20220907_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_master',
            name='via',
        ),
    ]
