# Generated by Django 3.2 on 2022-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0059_auto_20220921_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_master',
            name='division_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section_master',
            name='railway_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
