# Generated by Django 3.2 on 2022-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0061_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='loco_master',
            fields=[
                ('loco_id', models.AutoField(primary_key=True, serialize=False)),
                ('loco_cat', models.CharField(max_length=15, null=True)),
                ('loco_no', models.CharField(max_length=8, null=True)),
                ('mfg_name', models.CharField(max_length=10, null=True)),
                ('mfg_full_name', models.CharField(max_length=100, null=True)),
                ('loco_type', models.CharField(max_length=20, null=True)),
                ('loco_shed', models.CharField(max_length=10, null=True)),
                ('division_code', models.CharField(max_length=10, null=True)),
                ('railway_code', models.CharField(max_length=10, null=True)),
                ('gauge', models.CharField(max_length=2, null=True)),
                ('wheel_arr', models.CharField(max_length=10, null=True)),
                ('qty_built', models.IntegerField(null=True)),
                ('built_year', models.CharField(max_length=8, null=True)),
                ('turned_out_date', models.DateField(null=True)),
                ('shed_in_date', models.DateField(null=True)),
                ('doc_in_date', models.DateField(null=True)),
                ('power', models.CharField(max_length=10, null=True)),
                ('running_status', models.CharField(max_length=15, null=True)),
                ('Loco_description', models.CharField(max_length=30, null=True)),
                ('Loco_remarks', models.CharField(max_length=100, null=True)),
                ('max_capacity', models.CharField(max_length=100, null=True)),
                ('max_speed', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('lastmodified_by', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
