# Generated by Django 3.2 on 2022-09-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0019_auto_20220927_1751'),
        ('myadmin', '0062_loco_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype_master',
            name='concerned_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departmast'),
        ),
        migrations.AddField(
            model_name='loco_master',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_loco_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='loco_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_loco_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='runningroom_master',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_runningroom_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='section_master',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_section_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='station_master',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_station_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='train_master',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_train_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='train_master',
            name='primary_maint_depot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='train_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_train_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='train_master',
            name='secondary_maint_depot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departmast',
            name='delete_flag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.dropdown_options'),
        ),
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level_desig_temp',
            name='effectdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level_desig_temp1',
            name='effectdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loco_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loco_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roless',
            name='delete_flag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='runningroom_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningroom_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningroom_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_runningroom_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='section_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_section_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_station_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='stationcat_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationcat_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traincat_master',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traincat_master',
            name='lastmodified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
