# Generated by Django 3.2 on 2022-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0063_auto_20220927_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_master',
            name='rly_unit_code',
        ),
        migrations.AddField(
            model_name='post_master',
            name='post_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post_master',
            name='post_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
