# Generated by Django 3.2 on 2022-10-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0064_auto_20220929_1543'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='category',
            name='user_role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='departmast',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='level_desig',
            name='user_role',
            field=models.CharField(max_length=20, null=True),
        ),

 
    ]
