# Generated by Django 3.2 on 2022-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0065_auto_20221011_1045'),
    ]

    operations = [
       
    ]
