# Generated by Django 3.2 on 2022-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0066_auto_20221011_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_master',
            name='endkm',
        ),
        migrations.RemoveField(
            model_name='section_master',
            name='startkm',
        ),
        migrations.AddField(
            model_name='section_master',
            name='route',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='section_master',
            name='section_length',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='section_master',
            name='section_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
