# Generated by Django 3.2 on 2022-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0068_auto_20221018_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_menu',
            name='icons',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
