# Generated by Django 3.2 on 2022-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0069_custom_menu_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Railwayunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_description', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Unit_shortcode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='level_desig',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_master',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post_master',
            name='pc7_levelmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_master',
            name='pc7_levelmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
    ]
