# Generated by Django 3.2 on 2022-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0070_auto_20221206_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaylocationmaster',
            name='parent_rly_unit_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
