# Generated by Django 3.2 on 2023-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0071_railwaylocationmaster_parent_rly_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='wagon_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_type', models.CharField(max_length=50, null=True)),
                ('wagon_no', models.BigIntegerField(null=True)),
                ('owner_id', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(max_length=40, null=True)),
                ('dm_date', models.DateField(blank=True, null=True)),
                ('ic_date', models.DateField(blank=True, null=True)),
                ('manufacture_id', models.CharField(max_length=40, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('receiving_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
