# Generated by Django 3.2 on 2023-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0072_wagon_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype_master',
            name='disable_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiontype_master',
            name='lastmodified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
