# Generated by Django 3.2 on 2023-04-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0073_auto_20230226_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='my_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level_desig',
            name='station_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='level_desig',
            name='desig_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desig_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
