# Generated by Django 3.2 on 2023-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0074_auto_20230419_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='iem_hospmstr',
            fields=[
                ('iaihccid', models.AutoField(primary_key=True, serialize=False)),
                ('iavhcccode', models.CharField(blank=True, max_length=8, null=True)),
                ('iavhccfullname', models.CharField(blank=True, max_length=100, null=True)),
                ('iavhccshrtname', models.CharField(blank=True, max_length=30, null=True)),
                ('iavhccdk', models.CharField(blank=True, max_length=8, null=True)),
                ('iavhccsttncode', models.CharField(blank=True, max_length=4, null=True)),
                ('iavhcctype', models.CharField(blank=True, max_length=4, null=True)),
                ('iavhccdvsncode', models.CharField(blank=True, max_length=5, null=True)),
                ('iavhcczonecode', models.CharField(blank=True, max_length=4, null=True)),
                ('iavworkshopcode', models.CharField(blank=True, max_length=8, null=True)),
                ('iairlyunitcode', models.IntegerField(null=True)),
                ('iavcrtdby', models.CharField(blank=True, max_length=50, null=True)),
                ('iavmdfdby', models.CharField(blank=True, max_length=50, null=True)),
                ('iatcrtdon', models.DateTimeField(null=True)),
                ('iatmdfdon', models.DateTimeField(null=True)),
                ('iavstate', models.CharField(blank=True, max_length=20, null=True)),
                ('iavdist', models.CharField(blank=True, max_length=30, null=True)),
                ('iavcntry', models.CharField(blank=True, max_length=30, null=True)),
                ('iavpincode', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
