# Generated by Django 3.2 on 2023-04-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0128_myuser_guest_to'),
        ('myadmin', '0075_iem_hospmstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='posting_History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('done_by', models.CharField(max_length=25, null=True)),
                ('forwarded_to', models.CharField(max_length=25, null=True)),
                ('prev_desigination', models.CharField(max_length=100, null=True)),
                ('prev_parent_desig_code', models.CharField(max_length=15, null=True)),
                ('prev_contactnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('prev_official_email_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_station_name', models.CharField(max_length=100, null=True)),
                ('current_desigination', models.CharField(max_length=100, null=True)),
                ('current_parent_desig_code', models.CharField(max_length=15, null=True)),
                ('current_contactnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('current_official_email_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('current_station_name', models.CharField(max_length=100, null=True)),
                ('charge_type', models.CharField(max_length=1, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Forwarded', max_length=10)),
                ('created_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('current_department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_History_current_department_code', to='myadmin.departmast')),
                ('current_rly_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_History_current_rly_unit', to='myadmin.railwaylocationmaster')),
                ('empno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast')),
                ('prev_department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_History_prev_department_code', to='myadmin.departmast')),
                ('prev_rly_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_History_prev_rly_unit', to='myadmin.railwaylocationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='designation_Change_Request',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_by', models.CharField(max_length=25, null=True)),
                ('request_date', models.DateTimeField(null=True)),
                ('request_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('desigination', models.CharField(max_length=100, null=True)),
                ('prev_parent_desig_code', models.CharField(max_length=15, null=True)),
                ('prev_contactnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('prev_official_email_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_station_name', models.CharField(max_length=100, null=True)),
                ('prev_maxlevel', models.IntegerField(blank=True, null=True)),
                ('prev_minlevel', models.IntegerField(blank=True, null=True)),
                ('current_parent_desig_code', models.CharField(max_length=15, null=True)),
                ('current_contactnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('current_official_email_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('current_station_name', models.CharField(max_length=100, null=True)),
                ('current_maxlevel', models.IntegerField(blank=True, null=True)),
                ('current_minlevel', models.IntegerField(blank=True, null=True)),
                ('action_by', models.CharField(max_length=25, null=True)),
                ('action_date', models.DateTimeField(null=True)),
                ('action_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Forwarded', max_length=12)),
                ('request_type', models.CharField(default='Modification', max_length=12, null=True)),
                ('current_department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_Change_Request_curr_department_code', to='myadmin.departmast')),
                ('current_rly_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_Change_Request_curr_rly_unit', to='myadmin.railwaylocationmaster')),
                ('prev_department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_Change_Request_prev_department_code', to='myadmin.departmast')),
                ('prev_rly_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_Change_Request_prev_rly_unit', to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
