# Generated by Django 3.2 on 2023-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0076_designation_change_request_posting_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='iem_trainprofilemstr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iaitranid', models.IntegerField(null=True)),
                ('iavtranowngrly', models.CharField(blank=True, max_length=4, null=True)),
                ('iavtrannumb', models.CharField(blank=True, max_length=5, null=True)),
                ('iavtranname', models.CharField(blank=True, max_length=25, null=True)),
                ('mavtrantype', models.CharField(blank=True, max_length=4, null=True)),
                ('iavtranstyp', models.CharField(blank=True, max_length=4, null=True)),
                ('iadvaldfrom', models.DateTimeField(null=True)),
                ('iadvaldto', models.DateTimeField(null=True)),
                ('iavdaysofsrvc', models.CharField(blank=True, max_length=13, null=True)),
                ('iavorgn', models.CharField(blank=True, max_length=7, null=True)),
                ('iavdstn', models.CharField(blank=True, max_length=7, null=True)),
                ('iaideptime', models.IntegerField(null=True)),
                ('iaiarvltime', models.IntegerField(null=True)),
                ('iacgaug', models.CharField(blank=True, max_length=1, null=True)),
                ('iacuknwvldty', models.CharField(blank=True, max_length=1, null=True)),
                ('iacirctcflag', models.CharField(blank=True, max_length=1, null=True)),
                ('iavsrcstt', models.CharField(blank=True, max_length=4, null=True)),
                ('iavdstnstt', models.CharField(blank=True, max_length=10, null=True)),
                ('iairsrvflag', models.IntegerField(null=True)),
                ('iavhdayctgy', models.CharField(blank=True, max_length=4, null=True)),
                ('iavresncode', models.CharField(blank=True, max_length=8, null=True)),
                ('iacsrctrcn', models.CharField(blank=True, max_length=1, null=True)),
                ('iacsliptranflag', models.CharField(blank=True, max_length=1, null=True)),
                ('iacsliptype', models.CharField(blank=True, max_length=1, null=True)),
                ('iainrmlload', models.IntegerField(null=True)),
                ('iaimaxload', models.IntegerField(null=True)),
                ('iaiintlflag', models.IntegerField(null=True)),
                ('iaiftrbokgflag', models.IntegerField(null=True)),
                ('iavmaintrannumb', models.CharField(blank=True, max_length=5, null=True)),
                ('iavsliptrannumb', models.CharField(blank=True, max_length=5, null=True)),
                ('iainewtrannumb', models.IntegerField(null=True)),
                ('iavnewtranname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
