# Generated by Django 3.2 on 2023-05-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0077_iem_trainprofilemstr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iem_trainprofilemstr',
            new_name='iem_tranprofmstr',
        ),
    ]
