# Generated by Django 3.2 on 2023-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0078_rename_iem_trainprofilemstr_iem_tranprofmstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_sub_category_master',
            fields=[
                ('sub_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('sub_category', models.CharField(max_length=20, null=True)),
                ('disable_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category_master',
            fields=[
                ('sub_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('sub_category', models.CharField(max_length=20, null=True)),
                ('disable_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inspectiontype_master',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontype_master',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
