# Generated by Django 3.2 on 2023-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0079_auto_20230511_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='iem_transch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iaitranid', models.IntegerField(null=True)),
                ('iavtrannumb', models.CharField(blank=True, max_length=6, null=True)),
                ('iaisqncnumb', models.IntegerField(null=True)),
                ('iavzonecode', models.CharField(blank=True, max_length=4, null=True)),
                ('iavdvsncode', models.CharField(blank=True, max_length=4, null=True)),
                ('iavsttncode', models.CharField(blank=True, max_length=4, null=True)),
                ('iacclsflag', models.CharField(blank=True, max_length=1, null=True)),
                ('iaiwttarvl', models.IntegerField(null=True)),
                ('iaiwttdprt', models.IntegerField(null=True)),
                ('iachaltflag', models.CharField(blank=True, max_length=1, null=True)),
                ('iaiwttdayofrun', models.IntegerField(null=True)),
                ('iaipttdprt', models.IntegerField(null=True)),
                ('iaipttarvl', models.IntegerField(null=True)),
                ('iairuntime', models.IntegerField(null=True)),
                ('iaiacctime', models.IntegerField(null=True)),
                ('iaidectime', models.IntegerField(null=True)),
                ('iaitrfcalwc', models.IntegerField(null=True)),
                ('iaienggalwc', models.IntegerField(null=True)),
                ('iaicstrtime', models.IntegerField(null=True)),
                ('iavcstrresn', models.CharField(blank=True, max_length=64, null=True)),
                ('iacxingflag', models.CharField(blank=True, max_length=1, null=True)),
                ('iavxingtran', models.CharField(blank=True, max_length=30, null=True)),
                ('iavxingtime', models.CharField(blank=True, max_length=20, null=True)),
                ('iaiintrdist', models.IntegerField(null=True)),
                ('iavpltfnumb', models.CharField(blank=True, max_length=80, null=True)),
                ('iaccrewchng', models.CharField(blank=True, max_length=1, null=True)),
                ('iaclocochng', models.CharField(blank=True, max_length=1, null=True)),
                ('iacrvslsttn', models.CharField(blank=True, max_length=1, null=True)),
                ('iavtrcncode', models.CharField(blank=True, max_length=20, null=True)),
                ('iavcrewchngcode', models.CharField(blank=True, max_length=20, null=True)),
                ('iacgarbg', models.CharField(blank=True, max_length=1, null=True)),
                ('iacwater', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
