# Generated by Django 3.2 on 2023-05-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0080_iem_transch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype_master',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.sub_category_master'),
        ),
        migrations.AlterField(
            model_name='iem_transch',
            name='iaiintrdist',
            field=models.FloatField(null=True),
        ),
    ]
