# Generated by Django 3.2 on 2023-05-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0081_auto_20230519_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iem_hospmstr',
            name='iavhccdvsncode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iem_tranprofmstr',
            name='iainewtrannumb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iem_tranprofmstr',
            name='iavmaintrannumb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iem_tranprofmstr',
            name='iavsliptrannumb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iem_tranprofmstr',
            name='iavtrannumb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='trainMaster',
            fields=[
                ('tnid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('trainid', models.IntegerField(null=True)),
                ('train_no', models.CharField(blank=True, max_length=5, null=True)),
                ('train_name', models.CharField(blank=True, max_length=25, null=True)),
                ('org_railway_code', models.CharField(blank=True, max_length=4, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_on', models.DateTimeField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('passing_division', models.CharField(blank=True, max_length=300, null=True)),
                ('passing_rly', models.CharField(blank=True, max_length=300, null=True)),
                ('org_rly_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railwaystrainMaster', to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
