# Generated by Django 3.2 on 2023-05-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0083_delete_trainmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainMaster',
            fields=[
                ('tnid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('trainid', models.IntegerField(null=True)),
                ('train_no', models.CharField(blank=True, max_length=5, null=True)),
                ('train_name', models.CharField(blank=True, max_length=25, null=True)),
                ('org_railway_code', models.CharField(blank=True, max_length=4, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_on', models.DateTimeField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('passing_division', models.CharField(blank=True, max_length=300, null=True)),
                ('passing_rly', models.CharField(blank=True, max_length=300, null=True)),
                ('org_rly_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railwaystrainMaster', to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
