# Generated by Django 3.2 on 2023-06-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0084_trainmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_no', models.CharField(max_length=8, null=True)),
                ('coach_id', models.IntegerField(null=True)),
                ('coach_type', models.CharField(blank=True, max_length=15, null=True)),
                ('coach_owning_rly', models.CharField(max_length=4, null=True)),
                ('coach_owning_div', models.CharField(max_length=4, null=True)),
                ('base_depot', models.CharField(max_length=10, null=True)),
                ('nominated_workshop', models.CharField(blank=True, max_length=10, null=True)),
                ('coach_category', models.CharField(max_length=20, null=True)),
                ('max_speed', models.IntegerField(null=True)),
                ('manufacturer', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, null=True)),
                ('sub_category', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('reported_date', models.DateTimeField(auto_now=True, null=True)),
                ('cris_remarks', models.TextField(null=True)),
                ('status', models.IntegerField(default=0, max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('level_desig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
