# Generated by Django 3.2 on 2023-06-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0085_coach_master_feedback_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback_Report',
        ),
    ]
