# Generated by Django 3.2 on 2023-06-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0086_delete_feedback_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, null=True)),
                ('sub_category', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('reported_date', models.DateTimeField(auto_now=True, null=True)),
                ('cris_remarks', models.TextField(null=True)),
                ('status', models.IntegerField(default=0, max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('level_desig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
