# Generated by Django 3.2 on 2023-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0087_feedback_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_report',
            name='cris_remarks_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback_report',
            name='feedback_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
