# Generated by Django 3.2 on 2023-06-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0088_auto_20230606_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor_details',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('actorName', models.CharField(max_length=20)),
                ('tableName', models.CharField(max_length=30)),
                ('colName', models.CharField(max_length=50)),
                ('filterName', models.CharField(max_length=20, null=True)),
                ('filterValue', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='asset_master',
            fields=[
                ('asset_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('asset_category', models.CharField(max_length=20, null=True)),
                ('disable_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='actor_with_inspType',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('disable_flag', models.BooleanField(default=False)),
                ('actorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.actor_details')),
                ('inspType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.inspectiontype_master')),
            ],
        ),
        migrations.AddField(
            model_name='inspectiontype_master',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.asset_master'),
        ),
    ]
