# Generated by Django 3.2 on 2023-06-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0089_auto_20230615_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_details',
            name='color_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actor_details',
            name='viewColumn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor_details',
            name='viewFilter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actor_details',
            name='viewName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
