# Generated by Django 3.2 on 2023-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0090_auto_20230615_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='iem_crewmstr',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('iachqcode', models.CharField(blank=True, max_length=4, null=True)),
                ('iavcrewid', models.CharField(blank=True, max_length=8, null=True)),
                ('iavname', models.CharField(blank=True, max_length=60, null=True)),
                ('iavoff', models.CharField(blank=True, max_length=25, null=True)),
                ('iavcrewdesg', models.CharField(blank=True, max_length=25, null=True)),
                ('iabmoblnumb', models.BigIntegerField(blank=True, max_length=4, null=True)),
                ('iavcrewtype', models.CharField(blank=True, max_length=4, null=True)),
                ('iadapntdate', models.DateField(blank=True, null=True)),
                ('iacvisn', models.CharField(blank=True, max_length=4, null=True)),
                ('iacalch', models.CharField(blank=True, max_length=1, null=True)),
                ('iavinacstts', models.CharField(blank=True, max_length=10, null=True)),
                ('iavtrctn', models.CharField(blank=True, max_length=50, null=True)),
                ('iavliid', models.CharField(blank=True, max_length=10, null=True)),
                ('iaclrdue', models.CharField(blank=True, max_length=1, null=True)),
                ('iaccoch', models.CharField(blank=True, max_length=2, null=True)),
                ('iavorgtype', models.CharField(blank=True, max_length=4, null=True)),
                ('iadinitmed', models.DateField(blank=True, null=True)),
                ('iavempnumb', models.CharField(blank=True, max_length=30, null=True)),
                ('iavcrewbaseid', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback_report',
            name='cris_image',
            field=models.ImageField(blank=True, null=True, upload_to='cris_images/'),
        ),
    ]
