# Generated by Django 3.2 on 2023-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0091_auto_20230626_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category_master',
            name='sub_category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
