# Generated by Django 3.2 on 2023-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0092_alter_sub_category_master_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_details',
            name='viewactorName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
