# Generated by Django 3.2 on 2023-07-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0093_actor_details_viewactorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='rlyhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rllongdesc', models.CharField(max_length=30, null=True)),
                ('rlshortcode', models.CharField(max_length=100, null=True)),
                ('rltype', models.CharField(max_length=5, null=True)),
                ('head_dlevel', models.CharField(max_length=100, null=True)),
                ('rly_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
