# Generated by Django 3.2 on 2023-08-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0094_rlyhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rlyhead',
            name='rly_code',
        ),
        migrations.AddField(
            model_name='category',
            name='hierarchy_level',
            field=models.IntegerField(null=True),
        ),
    ]
