# Generated by Django 3.2 on 2023-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0095_auto_20230801_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='div_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='level_desig',
            name='hq_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
