# Generated by Django 3.2 on 2023-08-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0096_auto_20230802_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_desig',
            name='div_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_id', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='level_desig',
            name='hq_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hq_id', to='myadmin.railwaylocationmaster'),
        ),
    ]
