# Generated by Django 3.2 on 2023-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0097_auto_20230802_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='hierarchy_level',
            field=models.IntegerField(null=True),
        ),
    ]
