# Generated by Django 3.2 on 2023-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0098_level_desig_hierarchy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='iem_hospmstr',
            name='iaidivunitcode',
            field=models.IntegerField(null=True),
        ),
    ]
