# Generated by Django 3.2 on 2023-08-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0099_iem_hospmstr_iaidivunitcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='iem_crewmstr',
            name='div_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_division_crew_master', to='myadmin.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='iem_crewmstr',
            name='division_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iem_crewmstr',
            name='railway_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iem_crewmstr',
            name='rly_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaylocation_master_railways_crew_master', to='myadmin.railwaylocationmaster'),
        ),
    ]
