# Generated by Django 3.2 on 2023-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0100_auto_20230830_1703'),
    ]
