# Generated by Django 3.2 on 2023-09-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0101_alter_railwaylocationmaster_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype_master',
            name='other_entity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category_master',
            name='sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
