# Generated by Django 3.2 on 2023-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0102_auto_20230913_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_master',
            name='station_cat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='station_name',
            field=models.CharField(max_length=100),
        ),
    ]
