# Generated by Django 3.2 on 2023-11-14 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0103_auto_20230925_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_preferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('dashboard', models.CharField(max_length=30, null=True)),
                ('myuser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
