# Generated by Django 3.2 on 2023-11-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0104_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_preference_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(max_length=5, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=30, null=True)),
                ('url', models.CharField(max_length=150, null=True)),
                ('lastmodified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_preferences',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='user_preferences',
            name='lastmodified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_preferences',
            name='for_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_for', to='myadmin.user_preference_master'),
        ),
        migrations.AddField(
            model_name='user_preferences',
            name='value_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_value', to='myadmin.user_preference_master'),
        ),
    ]
