# Generated by Django 3.2 on 2023-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0105_auto_20231114_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendency_dashboard_like_crb',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
