# Generated by Django 3.2 on 2024-01-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0106_pendency_dashboard_like_crb'),
    ]

    operations = [
        migrations.CreateModel(
            name='empmast_nonrly',
            fields=[
                ('ref_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('empno', models.CharField(max_length=20)),
                ('orderid', models.CharField(blank=True, max_length=20, null=True)),
                ('empname', models.CharField(max_length=50)),
                ('empmname', models.CharField(blank=True, max_length=50, null=True)),
                ('emplname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contactno', models.CharField(blank=True, max_length=10, null=True)),
                ('railwaygroup', models.CharField(blank=True, max_length=1, null=True)),
                ('pc7_level', models.CharField(max_length=2, null=True)),
                ('service_status', models.CharField(default='DEPUTATION OUTSIDE', max_length=30)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('desig_longdesc', models.CharField(max_length=300, null=True)),
                ('station_des', models.CharField(max_length=100, null=True)),
                ('dept_desc', models.CharField(max_length=50, null=True)),
                ('currentzone', models.CharField(blank=True, max_length=50, null=True)),
                ('currentunitdivision', models.CharField(blank=True, max_length=100, null=True)),
                ('rl_type', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_modified_by', models.CharField(blank=True, default='self', max_length=20, null=True)),
                ('profile_modified_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('rly_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmast_nonrly_rly_id', to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
