# Generated by Django 3.2 on 2024-01-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0107_empmast_nonrly'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmast_nonrly',
            name='link_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empmast_nonrly',
            name='link_designation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='empmast_nonrly',
            name='profile_accepted_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empmast_nonrly',
            name='profile_accepted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empmast_nonrly',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
