# Generated by Django 3.2 on 2024-03-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0108_auto_20240112_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='customized_panel',
            fields=[
                ('panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('panel_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_member', to='myadmin.level_desig')),
                ('panel_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_of', to='myadmin.level_desig')),
            ],
        ),
    ]
