# Generated by Django 3.2 on 2024-03-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0109_customized_panel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customized_panel',
        ),
    ]
