# Generated by Django 3.2 on 2025-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0111_customized_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdms_coach_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_number', models.CharField(max_length=20, null=True)),
                ('coach_id', models.IntegerField()),
                ('owning_rly', models.CharField(max_length=10, null=True)),
                ('owning_div', models.CharField(max_length=10, null=True)),
                ('owning_depot', models.CharField(max_length=10, null=True)),
                ('rfid_tag', models.CharField(max_length=1, null=True)),
                ('coach_status', models.CharField(max_length=30, null=True)),
                ('coach_gauge', models.CharField(max_length=10, null=True)),
                ('tare_weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('max_speed', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fitness_type', models.CharField(max_length=10, null=True)),
                ('bio_toilet_fitted', models.CharField(max_length=5, null=True)),
                ('coupling_type', models.CharField(max_length=10, null=True)),
                ('manufacturer', models.CharField(max_length=15, null=True)),
                ('built_date', models.CharField(max_length=10, null=True)),
                ('commissioning_date', models.CharField(max_length=10, null=True)),
                ('condemnation_date', models.CharField(max_length=10, null=True)),
                ('seat_layout_variant_no', models.CharField(max_length=20, null=True)),
                ('coach_type', models.CharField(max_length=20, null=True)),
                ('coach_ac_flag', models.CharField(max_length=1, null=True)),
                ('coach_category', models.CharField(max_length=10, null=True)),
                ('factory_turnout_date', models.CharField(max_length=10, null=True)),
                ('power_generation_type', models.CharField(max_length=12, null=True)),
                ('nominated_workshop', models.CharField(max_length=10, null=True)),
                ('temporary_unavailable', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
