# Generated by Django 3.2 on 2025-06-08 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0112_mdms_coach_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdms_coach_master',
            name='Designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='application_smoothness',
            field=models.IntegerField(null=True, verbose_name='Application Smoothness'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='compliance_marked',
            field=models.IntegerField(null=True, verbose_name='Compliances (Marked to Me)'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='copy_to',
            field=models.IntegerField(null=True, verbose_name='COPY TO'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='dashboard',
            field=models.IntegerField(null=True, verbose_name='Dashboard'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='design_code',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='inspection_accuracy',
            field=models.IntegerField(null=True, verbose_name='Accuracy of Inspection Data'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='mom',
            field=models.IntegerField(null=True, verbose_name='Minutes of Meeting'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='my_inspection',
            field=models.IntegerField(null=True, verbose_name='My Inspection'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='overall_experience',
            field=models.IntegerField(null=True, verbose_name='Overall Experience'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='performance_speed',
            field=models.IntegerField(null=True, verbose_name='Performance Speed'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='reported_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='reports',
            field=models.IntegerField(null=True, verbose_name='Reports'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='search',
            field=models.IntegerField(null=True, verbose_name='Search'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='suggestions',
            field=models.CharField(max_length=1000, null=True, verbose_name='Suggestions for Improvement'),
        ),
        migrations.AddField(
            model_name='mdms_coach_master',
            name='ui_design',
            field=models.IntegerField(null=True, verbose_name='UI Design of the Application'),
        ),
    ]
