# Generated by Django 3.2 on 2025-06-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0113_auto_20250608_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='application_smoothness',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='compliance_marked',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='copy_to',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='design_code',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='inspection_accuracy',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='mom',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='my_inspection',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='overall_experience',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='performance_speed',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='reported_date',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='search',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='mdms_coach_master',
            name='ui_design',
        ),
        migrations.CreateModel(
            name='FeedBack_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_accuracy', models.IntegerField(null=True, verbose_name='Accuracy of Inspection Data')),
                ('ui_design', models.IntegerField(null=True, verbose_name='UI Design of the Application')),
                ('performance_speed', models.IntegerField(null=True, verbose_name='Performance Speed')),
                ('application_smoothness', models.IntegerField(null=True, verbose_name='Application Smoothness')),
                ('dashboard', models.IntegerField(null=True, verbose_name='Dashboard')),
                ('my_inspection', models.IntegerField(null=True, verbose_name='My Inspection')),
                ('compliance_marked', models.IntegerField(null=True, verbose_name='Compliances (Marked to Me)')),
                ('mom', models.IntegerField(null=True, verbose_name='Minutes of Meeting')),
                ('search', models.IntegerField(null=True, verbose_name='Search')),
                ('copy_to', models.IntegerField(null=True, verbose_name='COPY TO')),
                ('reports', models.IntegerField(null=True, verbose_name='Reports')),
                ('suggestions', models.CharField(max_length=1000, null=True, verbose_name='Suggestions for Improvement')),
                ('overall_experience', models.IntegerField(null=True, verbose_name='Overall Experience')),
                ('Designation', models.CharField(max_length=200, null=True)),
                ('reported_date', models.DateTimeField(auto_now=True, null=True)),
                ('design_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
