# Generated by Django 3.2 on 2025-06-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0114_auto_20250608_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack_data',
        ),
    ]
