# Generated by Django 3.2 on 2025-06-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0116_feedback_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack_data',
        ),
    ]
