# Generated by Django 3.2 on 2025-06-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0118_feedback_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack_data',
        ),
    ]
