# Generated by Django 3.2 on 2025-06-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0119_delete_feedback_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_accuracy', models.IntegerField(null=True, verbose_name='Accuracy of Inspection Data')),
                ('ui_design', models.IntegerField(null=True, verbose_name='UI Design of the Application')),
                ('performance_speed', models.IntegerField(null=True, verbose_name='Performance Speed')),
                ('application_smoothness', models.IntegerField(null=True, verbose_name='Application Smoothness')),
                ('dashboard', models.IntegerField(null=True, verbose_name='Dashboard')),
                ('my_inspection', models.IntegerField(null=True, verbose_name='My Inspection')),
                ('compliance_marked', models.IntegerField(null=True, verbose_name='Compliances (Marked to Me)')),
                ('mom', models.IntegerField(null=True, verbose_name='Minutes of Meeting')),
                ('search', models.IntegerField(null=True, verbose_name='Search')),
                ('copy_to', models.IntegerField(null=True, verbose_name='COPY TO')),
                ('reports', models.IntegerField(null=True, verbose_name='Reports')),
                ('suggestions', models.CharField(max_length=1000, null=True, verbose_name='Suggestions for Improvement')),
                ('overall_experience', models.IntegerField(null=True, verbose_name='Overall Experience')),
                ('Designation', models.CharField(max_length=200, null=True)),
                ('reported_date', models.DateTimeField(auto_now=True, null=True)),
                ('design_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
