# Generated by Django 3.2 on 2022-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_reliabilty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50, null=True)),
                ('targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('targets_current_month', models.CharField(max_length=50, null=True)),
                ('progressive_current_month', models.CharField(max_length=50, null=True)),
                ('y_day_actual', models.CharField(max_length=50, null=True)),
                ('today_forecast', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capex_head_wise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50, null=True)),
                ('actual_exp', models.CharField(max_length=50, null=True)),
                ('exp_sept_2021', models.CharField(max_length=50, null=True)),
                ('utilization', models.CharField(max_length=50, null=True)),
                ('be', models.CharField(max_length=50, null=True)),
                ('be_mod', models.CharField(max_length=50, null=True)),
                ('exp_sept_2022', models.CharField(max_length=50, null=True)),
                ('utilization_be_mod', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capex_item_wise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50, null=True)),
                ('actual_exp', models.CharField(max_length=50, null=True)),
                ('exp_sept_2021', models.CharField(max_length=50, null=True)),
                ('utilization', models.CharField(max_length=50, null=True)),
                ('be', models.CharField(max_length=50, null=True)),
                ('be_mod', models.CharField(max_length=50, null=True)),
                ('exp_sept_2022', models.CharField(max_length=50, null=True)),
                ('utilization_be_mod', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capex_resource_wise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50, null=True)),
                ('actual_exp', models.CharField(max_length=50, null=True)),
                ('exp_sept_2021', models.CharField(max_length=50, null=True)),
                ('utilization', models.CharField(max_length=50, null=True)),
                ('be', models.CharField(max_length=50, null=True)),
                ('be_mod', models.CharField(max_length=50, null=True)),
                ('exp_sept_2022', models.CharField(max_length=50, null=True)),
                ('utilization_be_mod', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='earnings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('budget_targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('bp', models.CharField(max_length=50, null=True)),
                ('approx', models.CharField(max_length=50, null=True)),
                ('variation', models.CharField(max_length=50, null=True)),
                ('increase', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='infrastructure_creation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('infrastructure_works', models.CharField(max_length=50, null=True)),
                ('annual_target', models.CharField(max_length=50, null=True)),
                ('cum_targets', models.CharField(max_length=50, null=True)),
                ('cummulative_achieved', models.CharField(max_length=50, null=True)),
                ('variation', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loading_b3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
                ('se_dte', models.CharField(max_length=50, null=True)),
                ('budget_targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('bp', models.CharField(max_length=50, null=True)),
                ('approx', models.CharField(max_length=50, null=True)),
                ('variation', models.CharField(max_length=50, null=True)),
                ('increase', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loading_commodity_wise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=50, null=True)),
                ('targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('actuals_current_month', models.CharField(max_length=50, null=True)),
                ('var_over_ly', models.CharField(max_length=50, null=True)),
                ('var_over_target', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loading_zone_wise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('actuals_current_month', models.CharField(max_length=50, null=True)),
                ('var_over_ly', models.CharField(max_length=50, null=True)),
                ('var_over_target', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='punctuality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('train_count', models.CharField(max_length=50, null=True)),
                ('pp', models.CharField(max_length=50, null=True)),
                ('total_delay', models.CharField(max_length=50, null=True)),
                ('delay_per_train', models.CharField(max_length=50, null=True)),
                ('cause1', models.CharField(max_length=50, null=True)),
                ('cause2', models.CharField(max_length=50, null=True)),
                ('cause3', models.CharField(max_length=50, null=True)),
                ('cause4', models.CharField(max_length=50, null=True)),
                ('cause5', models.CharField(max_length=50, null=True)),
                ('cause6', models.CharField(max_length=50, null=True)),
                ('cause7', models.CharField(max_length=50, null=True)),
                ('cause8', models.CharField(max_length=50, null=True)),
                ('cause9', models.CharField(max_length=50, null=True)),
                ('cause10', models.CharField(max_length=50, null=True)),
                ('cause11', models.CharField(max_length=50, null=True)),
                ('cause12', models.CharField(max_length=50, null=True)),
                ('others', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rolling_stock_production',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50, null=True)),
                ('total_previous_year', models.IntegerField(null=True)),
                ('progressive_current_year', models.IntegerField(null=True)),
                ('same_month_of_previous_year', models.IntegerField(null=True)),
                ('progressive_current_month', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='safety',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_of_accident', models.CharField(max_length=50)),
                ('col1', models.IntegerField(null=True)),
                ('col2', models.IntegerField(null=True)),
                ('col3', models.IntegerField(null=True)),
                ('col4', models.IntegerField(null=True)),
                ('col5', models.IntegerField(null=True)),
                ('change', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
