# Generated by Django 3.2 on 2022-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='division_performa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=50, null=True)),
                ('cummulative', models.CharField(max_length=50, null=True)),
                ('current_month_py', models.CharField(max_length=50, null=True)),
                ('current_month', models.CharField(max_length=50, null=True)),
                ('current_month_variation', models.CharField(max_length=50, null=True)),
                ('current_year_py', models.CharField(max_length=50, null=True)),
                ('current_year', models.CharField(max_length=50, null=True)),
                ('current_year_variation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
