# Generated by Django 3.2 on 2022-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_division_performa'),
    ]

    operations = [
        migrations.CreateModel(
            name='owe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('budget_targets', models.CharField(max_length=50, null=True)),
                ('actuals', models.CharField(max_length=50, null=True)),
                ('bp', models.CharField(max_length=50, null=True)),
                ('approx', models.CharField(max_length=50, null=True)),
                ('variation', models.CharField(max_length=50, null=True)),
                ('increase', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
