# Generated by Django 3.2 on 2022-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_owe'),
    ]

    operations = [
        migrations.AddField(
            model_name='punctuality',
            name='cause13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='punctuality',
            name='cause14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='punctuality',
            name='cause15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='punctuality',
            name='cause16',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
