# Generated by Django 3.2 on 2022-10-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20221031_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='punctuality',
        ),
    ]
