# Generated by Django 3.2 on 2022-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_punctuality'),
    ]

    operations = [
        migrations.CreateModel(
            name='punctuality_dept',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50, null=True)),
                ('train_count', models.CharField(max_length=50, null=True)),
                ('pp', models.CharField(max_length=50, null=True)),
                ('total_delay', models.CharField(max_length=50, null=True)),
                ('delay_per_train', models.CharField(max_length=50, null=True)),
                ('cause1', models.CharField(max_length=50, null=True)),
                ('cause2', models.CharField(max_length=50, null=True)),
                ('cause3', models.CharField(max_length=50, null=True)),
                ('cause4', models.CharField(max_length=50, null=True)),
                ('cause5', models.CharField(max_length=50, null=True)),
                ('cause6', models.CharField(max_length=50, null=True)),
                ('cause7', models.CharField(max_length=50, null=True)),
                ('cause8', models.CharField(max_length=50, null=True)),
                ('cause9', models.CharField(max_length=50, null=True)),
                ('cause10', models.CharField(max_length=50, null=True)),
                ('cause11', models.CharField(max_length=50, null=True)),
                ('cause12', models.CharField(max_length=50, null=True)),
                ('cause13', models.CharField(max_length=50, null=True)),
                ('cause14', models.CharField(max_length=50, null=True)),
                ('cause15', models.CharField(max_length=50, null=True)),
                ('cause16', models.CharField(max_length=50, null=True)),
                ('others', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
