# Generated by Django 3.2 on 2022-12-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_parliament_bmwise_pendency_parliament_count_ls_rs_parliament_dirwise_pendency_parliament_myboardmemb'),
        ('home_page', '0008_parliament_bmwise_pendency_parliament_count_ls_rs_parliament_dirwise_pendency_parliament_myboardmemb'),
    ]

    operations = [
    ]
