# Generated by Django 3.2 on 2023-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_merge_20221215_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='parliament_countOfficerwiseTotal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dircode', models.IntegerField(null=True)),
                ('bmid', models.IntegerField(null=True)),
                ('countspecialmention', models.IntegerField(max_length=50, null=True)),
                ('countzerohour', models.IntegerField(max_length=50, null=True)),
                ('countpetition', models.IntegerField(max_length=50, null=True)),
                ('designame', models.CharField(max_length=50, null=True)),
                ('countrule377', models.IntegerField(max_length=50, null=True)),
                ('countass', models.IntegerField(max_length=50, null=True)),
                ('datecreatedon', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pendency_status_zone_div_dropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, null=True)),
                ('pendcountzone', models.IntegerField(max_length=50, null=True)),
                ('id3_6', models.IntegerField(max_length=50, null=True)),
                ('allid', models.IntegerField(max_length=50, null=True)),
                ('divpendid', models.IntegerField(max_length=50, null=True)),
                ('id0_3', models.IntegerField(max_length=50, null=True)),
                ('pendcount0_3', models.IntegerField(max_length=50, null=True)),
                ('id6_12', models.IntegerField(max_length=50, null=True)),
                ('zonecountpend', models.IntegerField(max_length=50, null=True)),
                ('zonecountall', models.IntegerField(max_length=50, null=True)),
                ('id12', models.IntegerField(max_length=50, null=True)),
                ('pendcount6_12', models.IntegerField(max_length=50, null=True)),
                ('pendcount3_6', models.IntegerField(max_length=50, null=True)),
                ('zonependid', models.IntegerField(max_length=50, null=True)),
                ('pendcount12', models.IntegerField(max_length=50, null=True)),
                ('divcountpend', models.IntegerField(max_length=50, null=True)),
                ('zoneunitcode', models.CharField(max_length=50, null=True)),
                ('datecreatedon', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
