# Generated by Django 3.2 on 2023-01-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_parliament_countofficerwisetotal_pendency_status_zone_div_dropdown'),
        ('home_page', '0010_parliament_countofficerwisetotal_pendency_status_zone_div_dropdown'),
    ]

    operations = [
    ]
